site_name: Interpretador G16
theme:
  name: material
  language: pt
  # features:
  #   - navigation.expand
  #   - navigation.sections
  #   - navigation.top
  #   - toc.integrate
  #   - content.code.copy

nav:
  - Início: index.md
  - Dificuldades:
      - Visão geral: Dificuldades/dificuldades.md
  - Planejamento:
      - Visão geral: Planejamento/planejamento.md

# markdown_extensions:
#   - admonition
#   - footnotes
#   - toc:
#       permalink: true
#   - tables
#   - pymdownx.details
#   - pymdownx.highlight
#   - pymdownx.superfences
#   - pymdownx.emoji